#!/usr/bin/env bash

set -eux

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<- EOT
  CREATE ROLE ${SAMPLE_CONFIG_POSTGRESQL_USER} WITH LOGIN PASSWORD '${SAMPLE_CONFIG_POSTGRESQL_PASSWORD}';

  CREATE DATABASE ${SAMPLE_CONFIG_POSTGRESQL_DBNAME};
  ALTER DATABASE ${SAMPLE_CONFIG_POSTGRESQL_DBNAME} OWNER TO ${SAMPLE_CONFIG_POSTGRESQL_USER};
EOT

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$SAMPLE_CONFIG_POSTGRESQL_DBNAME" <<- EOT
  CREATE EXTENSION postgis;
EOT
