services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    ports:
      - 5000:5000
    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      # - ./__init__.py:/pygeoapi/pygeoapi/api/__init__.py
      - ./newapi.py:/pygeoapi/pygeoapi/api/newapi.py
      - ./flask_app.py:/pygeoapi/flask_app.py
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_OPENAPI=/pygeoapi/local.openapi.yml
    entrypoint: /entrypoint.sh
